service_name: restaurant-service
display_name: "Restaurant Service"
language: python
deployment_platform: railway
docker_file: Dockerfile.prod
health_check_url: https://restaurant.forkline.com/health
python_versions: [3.9, 3.10]
deployment_secrets:
  - RAILWAY_TOKEN
environment_variables:
  - PYTHON_ENV=production
  - PRODUCTION_DOMAIN=forkline.com
build_steps:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - python -m pytest || echo "No tests found"
  - flake8 . || echo "No linting configured"
notification_icon: "🍽️"
subdomain: restaurant 