service_name: order-service
display_name: "Order Service"
language: java
deployment_platform: railway
docker_file: Dockerfile.prod
health_check_url: https://order.forkline.com/health
java_versions: [17, 21]
deployment_secrets:
  - RAILWAY_TOKEN
environment_variables:
  - JAVA_ENV=production
  - PRODUCTION_DOMAIN=forkline.com
build_steps:
  - mvn test || echo "No tests found"
  - mvn checkstyle:check || echo "No checkstyle configured"
notification_icon: "📋"
subdomain: order 