service_name: inventory-service
display_name: "Inventory Service"
language: python
deployment_platform: render
docker_file: Dockerfile.prod
health_check_url: https://inventory.forkline.com/health
python_versions: [3.9, 3.10]
deployment_secrets:
  - RENDER_INVENTORY_SERVICE_ID
  - RENDER_API_KEY
environment_variables:
  - PYTHON_ENV=production
  - PRODUCTION_DOMAIN=forkline.com
build_steps:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - python -m pytest || echo "No tests found"
  - flake8 . || echo "No linting configured"
notification_icon: "📦"
subdomain: inventory 