name: 🍽️ Menu Service - Production CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'backend/menu-service/**'
  pull_request:
    branches: [main]
    paths:
      - 'backend/menu-service/**'
  workflow_dispatch:
    inputs:
      force_deploy:
        description: 'Force production deployment'
        required: false
        default: false
        type: boolean

env:
  SERVICE_NAME: menu-service
  SERVICE_PATH: backend/menu-service
  REGISTRY: ghcr.io
  IMAGE_NAME: forkline/menu-service
  PRODUCTION_URL: https://menu.forkline.com

jobs:
  security-scan:
    name: 🔒 Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './backend/menu-service'
          format: 'sarif'
          output: 'trivy-results.sarif'

  build-test:
    name: 🧪 Build & Test
    runs-on: ubuntu-latest
    needs: security-scan
    strategy:
      matrix:
        python-version: [3.9, 3.10]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: backend/menu-service/requirements.txt
      - name: Install dependencies
        run: |
          cd backend/menu-service
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          cd backend/menu-service
          pip install pytest
          pytest tests/ -v || true

  deploy-production:
    name: 🚀 Deploy to Production
    runs-on: ubuntu-latest
    needs: build-test
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
      - name: Deploy to Render
        run: |
          echo "🚀 Deploying Menu Service to Render..."
          curl -X POST "${{ secrets.RENDER_WEBHOOK_MENU_SERVICE }}" \
            -H "Content-Type: application/json" \
            -d '{"service": "menu-service", "environment": "production"}'
      - name: Health check
        run: |
          echo "🔍 Performing health check..."
          sleep 90
          curl -f -s "${{ env.PRODUCTION_URL }}/health" || echo "❌ Health check failed" 