name: 📅 Booking Service - Production CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'backend/booking-service/**'
  pull_request:
    branches: [main]
    paths:
      - 'backend/booking-service/**'
  workflow_dispatch:
    inputs:
      force_deploy:
        description: 'Force production deployment'
        required: false
        default: false
        type: boolean

env:
  SERVICE_NAME: booking-service
  SERVICE_PATH: backend/booking-service
  REGISTRY: ghcr.io
  IMAGE_NAME: forkline/booking-service
  PRODUCTION_URL: https://booking.forkline.com

jobs:
  security-scan:
    name: 🔒 Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './backend/booking-service'
          format: 'sarif'
          output: 'trivy-results.sarif'

  build-test:
    name: 🧪 Build & Test
    runs-on: ubuntu-latest
    needs: security-scan
    strategy:
      matrix:
        go-version: [1.20, 1.21]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: backend/booking-service/go.sum
      - name: Install dependencies
        run: |
          cd backend/booking-service
          go mod download
      - name: Run tests
        run: |
          cd backend/booking-service
          go test ./... -v || true
      - name: Build application
        run: |
          cd backend/booking-service
          go build -o booking-service ./cmd/main.go

  deploy-production:
    name: 🚀 Deploy to Production
    runs-on: ubuntu-latest
    needs: build-test
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
      - name: Deploy to Render
        run: |
          echo "🚀 Deploying Booking Service to Render..."
          curl -X POST "${{ secrets.RENDER_WEBHOOK_BOOKING_SERVICE }}" \
            -H "Content-Type: application/json" \
            -d '{"service": "booking-service", "environment": "production"}'
      - name: Health check
        run: |
          echo "🔍 Performing health check..."
          sleep 90
          curl -f -s "${{ env.PRODUCTION_URL }}/health" || echo "❌ Health check failed" 